export const navItems = {
	overview: [
		{
			title: 'Overview',
			header: true,
			link: '',
			id: 1,
		},
		{
			title: 'Feed',
			icon: '/images/feed-icon.svg',
			iconActive: '/images/feed-icon-active.svg',
			link: '/feed',
			id: 2,
		},
		{
			title: 'Bookmarks',
			icon: '/images/bookmark-icon.svg',
			iconActive: '/images/bookmark-icon.svg',
			link: '#',
			id: 3,
		},
		// {
		// 	title: 'Team Blogs',
		// 	icon: '/images/team-icon.svg',
		// 	iconActive: '/images/team-icon.svg',
		// 	link: '#',
		// 	id: 4,
		// },
		{
			title: 'Drafts',
			icon: '/images/draft-icon.svg',
			iconActive: '/images/draft-icon-active.svg',
			link: '/draft',
			id: 5,
		},
		// {
		// 	title: 'Analytics',
		// 	icon: '/images/analytics-icon.svg',
		// 	iconActive: '/images/analytics-icon.svg',
		// 	link: '#',
		// 	id: 6,
		// },
	],
	trends: [
		{
			title: 'Trending Tags',
			icon: '/images/trend-icon.svg',
			link: '',
			header: true,
			id: 1,
		},
		{
			title: 'Programming',
			icon: '',
			link: '#',
			id: 2,
		},
		{
			title: 'Data Science',
			icon: '',
			link: '#',
			id: 3,
		},
		{
			title: 'Technology',
			icon: '',
			link: '#',
			id: 4,
		},
		{
			title: 'Machine Learning',
			icon: '',
			link: '#',
			id: 5,
		},
		{
			title: 'Politics',
			icon: '',
			link: '#',
			id: 6,
		},
		{
			title: 'See all',
			icon: '',
			link: '#',
			id: 6,
		},
	],
};
